[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  port = 8889

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "no-store"
